import java.util.ArrayList;
import java.util.Collections;

/**
 * Represents a standard 52-card poker deck.
 * Builds the deck with cards from 2 to Ace for each suit, assigns appropriate face card names, and shuffles the deck.
 * Extends the Deck class and overrides the buildDeck method to generate poker-specific card values.
 * This deck is suitable for games that use a standard poker deck, including Blackjack.
 *
 * @author Tyler Lang
 * @version 2025.04.03
 */
public class PokerDeck extends Deck
{
    /**
     * Constructs a new PokerDeck by calling the superclass constructor.
     * The actual cards are generated by the buildDeck method.
     */
    public PokerDeck()
    {
        super();
        buildDeck();
    }

    /**
     * Builds a standard 52-card poker deck.
     * Creates cards from 2 to Ace for each suit, assigns names to face cards,
     * stores them in a list, and shuffles the deck.
     * Overrides the abstract method in the Deck class.
     */
    @Override
    public void buildDeck()
    {
        String name = "";
        ArrayList<Card> cards = new ArrayList<>();

        for(Suit suit : Suit.values())
        {
            for(int i = 2; i <= 14; i++)
            {
                switch(i)
                {
                    case 11 -> name = "Jack";
                    case 12 -> name = "Queen";
                    case 13 -> name = "King";
                    case 14 -> name = "Ace";
                    default -> name = String.valueOf(i);
                }

                cards.add(new Card(suit, i, false, name));
            }
        }

        Collections.shuffle(cards);
        super.setCards(cards);
    }
}
